export enum MovementType {
  ENTRY_BY_PURCHASE = 1,
  ENTRY_BY_RETURN = 2,
  ENTRY_BY_ASSISTANCE = 3,
  ENTRY_BY_TRANSFER = 4,
  EXIT_BY_SALE = 20,
  EXIT_BY_DISPOSAL = 21,
  EXIT_BY_ASSISTANCE = 22,
  EXIT_BY_TRANSFER = 23,
  EXIT_BY_RETURN = 24,
}
